app:
  port: "8080"
  name: "Raxmet"
  version: "1.0.0"
  env: "development"
  debug: true
  maxBody: 50
  maxWorkers: 10
  maxRequests: 100

database:
  host: "localhost"
  user: "raxmet"
  password: "raxmet_db"
  name: "raxmet"
  port: 5432

minio:
  endpoint: "localhost:9000"
  accessKey: "minio_user"
  secretKey: "minio_pass"
  bucket: "my-bucket"

redis:
  host: "localhost"
  port: 6379
