app:
  name: "Raxmet"
  version: "1.0.0"
  env: "development"
  debug: true

server:
  port: "8080"

database:
  host: "localhost"
  user: "your_db_user"
  password: "your_db_password"
  name: "splitwise_db"
  port: 5432

minio:
  endpoint: "localhost:9000"
  accessKey: "minio_user"
  secretKey: "minio_pass"
  bucket: "my-bucket"

redis:
  host: "localhost"
  port: 6379
